const p0ToP1 = [
  ['Microorganisms','Bacteria','Barren, Ice, Oceanic, Temperate'], ['Carbon Compounds','Biofuels','Barren, Oceanic, Temperate'],
  ['Planktic Colonies','Biomass','Ice, Oceanic'], ['Non-CS Crystals','Chiral Structures','Lava, Plasma'],
  ['Ionic Solutions','Electrolytes','Gas, Storm'], ['Autotrophs','Industrial Fibers','Temperate'],
  ['Reactive Gas','Oxidizing Compound','Gas'], ['Noble Gas','Oxygen','Gas, Ice, Storm'],
  ['Suspended Plasma','Plasmoids','Lava, Plasma, Storm'], ['Noble Metals','Precious Metals','Barren, Plasma'],
  ['Complex Organisms','Proteins','Oceanic, Temperate'], ['Base Metals','Reactive Metals','Barren, Gas, Lava, Plasma, Storm'],
  ['Felsic Magma','Silicon','Lava'], ['Heavy Metals','Toxic Metals','Ice, Lava, Plasma'],
  ['Aqueous Liquids','Water','Barren, Gas, Ice, Oceanic, Storm, Temperate']
];
const recipes = {
  P2: {
    'Biocells':['Precious Metals','Biofuels'], 'Construction Blocks':['Toxic Metals','Reactive Metals'], 'Consumer Electronics':['Chiral Structures','Toxic Metals'], 'Coolant':['Water','Electrolytes'],
    'Enriched Uranium':['Toxic Metals','Precious Metals'], 'Fertilizer':['Proteins','Bacteria'], 'Genetically Enhanced Livestock':['Biomass','Proteins'], 'Livestock':['Biofuels','Proteins'],
    'Mechanical Parts':['Precious Metals','Reactive Metals'], 'Microfiber Shielding':['Silicon','Industrial Fibers'], 'Miniature Electronics':['Silicon','Chiral Structures'], 'Nanites':['Reactive Metals','Bacteria'],
    'Oxides':['Oxygen','Oxidizing Compound'], 'Polyaramids':['Industrial Fibers','Oxidizing Compound'], 'Polytextiles':['Industrial Fibers','Biofuels'], 'Rocket Fuel':['Electrolytes','Plasmoids'],
    'Silicate Glass':['Silicon','Oxidizing Compound'], 'Superconductors':['Water','Plasmoids'], 'Supertensile Plastics':['Oxygen','Biomass'], 'Synthetic Oil':['Oxygen','Electrolytes'],
    'Test Cultures':['Water','Bacteria'], 'Transmitter':['Chiral Structures','Plasmoids'], 'Viral Agent':['Biomass','Bacteria'], 'Water-Cooled CPU':['Water','Reactive Metals']
  },
  P3: {
    'Biotech Research Reports':['Nanites','Livestock','Construction Blocks'], 'Camera Drones':['Silicate Glass','Rocket Fuel'], 'Condensates':['Oxides','Coolant'],
    'Cryoprotectant Solution':['Test Cultures','Synthetic Oil','Fertilizer'], 'Data Chips':['Supertensile Plastics','Microfiber Shielding'], 'Gel-Matrix Biopaste':['Oxides','Biocells','Superconductors'],
    'Guidance Systems':['Water-Cooled CPU','Transmitter'], 'Hazmat Detection Systems':['Polytextiles','Viral Agent','Transmitter'], 'Hermetic Membranes':['Polyaramids','Genetically Enhanced Livestock'],
    'High-Tech Transmitters':['Polyaramids','Transmitter'], 'Industrial Explosives':['Fertilizer','Polytextiles'], 'Neocoms':['Biocells','Silicate Glass'], 'Nuclear Reactors':['Microfiber Shielding','Enriched Uranium'],
    'Planetary Vehicles':['Supertensile Plastics','Mechanical Parts','Miniature Electronics'], 'Robotics':['Mechanical Parts','Consumer Electronics'], 'Smartfab Units':['Construction Blocks','Miniature Electronics'],
    'Supercomputers':['Water-Cooled CPU','Coolant','Consumer Electronics'], 'Synthetic Synapses':['Supertensile Plastics','Test Cultures'], 'Transcranial Microcontrollers':['Biocells','Nanites'],
    'Ukomi Superconductors':['Synthetic Oil','Superconductors'], 'Vaccines':['Livestock','Viral Agent']
  },
  P4: {
    'Broadcast Node':['Neocoms','Data Chips','High-Tech Transmitters'], 'Integrity Response Drones':['Gel-Matrix Biopaste','Hazmat Detection Systems','Planetary Vehicles'],
    'Nano-Factory':['Industrial Explosives','Ukomi Superconductors','Reactive Metals'], 'Organic Mortar Applicators':['Condensates','Robotics','Bacteria'],
    'Recursive Computing Module':['Synthetic Synapses','Guidance Systems','Transcranial Microcontrollers'], 'Self-Harmonizing Power Core':['Camera Drones','Nuclear Reactors','Hermetic Membranes'],
    'Sterile Conduits':['Smartfab Units','Vaccines','Water'], 'Wetware Mainframe':['Supercomputers','Biotech Research Reports','Cryoprotectant Solution']
  }
};
const tierNames = ['P0','P1','P2','P3','P4'];
const minerFiles = {
  'Bacteria':['Miner/00/Miner - 00 - Bacteria.json','Miner/LS/Miner - LS - Bacteria.json'], 'Biofuels':['Miner/00/Miner - 00 - Biofuels.json','Miner/LS/Miner - LS - Temperate - Biofuels.json'],
  'Biomass':['Miner/00/Miner - 00 - Biomass.json','Miner/LS/Miner - LS - Biomass.json'], 'Chiral Structures':['Miner/00/Miner - 00 - Chiral Stuctures.json','Miner/LS/Miner - LS - Chiral Structures.json'],
  'Electrolytes':['Miner/00/Miner - 00 - Electrolytes.json','Miner/LS/Miner - LS - Storm - Electrolytes.json'], 'Industrial Fibers':['Miner/00/Miner - 00 - Industrial Fibers.json','Miner/LS/Miner - LS - Temperate - Industrial Fibers.json'],
  'Oxidizing Compound':['Miner/00/Miner - 00 - Oxidizing Compound.json','Miner/LS/Miner - LS - Oxidizing Compound.json'], 'Oxygen':['Miner/00/Miner - 00 - Oxygen.json','Miner/LS/Miner - LS - Oxygen.json'],
  'Plasmoids':['Miner/00/Miner - 00 - Plasmoids.json','Miner/LS/Miner - LS - Plasmoids.json'], 'Precious Metals':['Miner/00/Miner - 00 - Precious Metals.json','Miner/LS/Miner - LS - Precious Metals.json'],
  'Proteins':['Miner/00/Miner - 00 - Proteins.json','Miner/LS/Miner - LS - Proteins.json'], 'Reactive Metals':['Miner/00/Miner - 00 - Reactive Metals.json','Miner/LS/Miner - LS - Reactive Metals.json'],
  'Silicon':['Miner/00/Miner - 00 - Silicon.json','Miner/LS/Miner - LS - Silicon.json'], 'Toxic Metals':['Miner/00/Miner - 00 - Toxic Metals.json','Miner/LS/Miner - LS - Toxic Metals.json'],
  'Water':['Miner/00/Miner - 00 - Water.json','Miner/LS/Miner - LS - Water.json']
};
const nodes = [], nodeByName = new Map(), edges = [];
function addNode(name, tier, planets='') { if (!nodeByName.has(name)) { const node={name,tier,planets}; nodeByName.set(name,node); nodes.push(node); } }
p0ToP1.forEach(([input, output, planets]) => { addNode(input,'P0',planets); addNode(output,'P1'); edges.push([input,output]); });
Object.entries(recipes).forEach(([tier, map]) => Object.entries(map).forEach(([output, inputs]) => { addNode(output,tier); inputs.forEach(input => { addNode(input, tierNames[tierNames.indexOf(tier)-1]); edges.push([input,output]); }); }));
const svg = document.getElementById('graph'), ns = 'http://www.w3.org/2000/svg';
const positions = new Map(), colX = {P0:220,P1:465,P2:710,P3:955,P4:1200}, nodeW=185, nodeH=48, gap=8;
const verticalGap = {P0:nodeH+gap, P1:nodeH+gap, P2:nodeH+gap, P3:nodeH+gap, P4:nodeH+gap};
tierNames.forEach(tier => { const list=nodes.filter(node=>node.tier===tier); list.forEach((node,index)=>positions.set(node.name,{x:colX[tier],y:78+index*verticalGap[tier]})); const label=document.createElementNS(ns,'text'); label.setAttribute('x',colX[tier]); label.setAttribute('y','29'); label.setAttribute('class','tier-label'); label.textContent=tier; svg.appendChild(label); });
const graphHeight = Math.max(...tierNames.map(tier => nodes.filter(node=>node.tier===tier).length ? Math.max(...nodes.filter(node=>node.tier===tier).map(node=>positions.get(node.name).y + nodeH)) : 0)) + 30;
svg.setAttribute('viewBox',`0 0 1410 ${Math.max(1760,graphHeight)}`);
const edgeEls=[];
edges.forEach(([from,to])=>{ const start=positions.get(from), end=positions.get(to), path=document.createElementNS(ns,'path'); path.setAttribute('d',`M ${start.x+nodeW} ${start.y+nodeH/2} C ${start.x+nodeW+35} ${start.y+nodeH/2}, ${end.x-35} ${end.y+nodeH/2}, ${end.x} ${end.y+nodeH/2}`); path.setAttribute('class','edge'); path.dataset.from=from; path.dataset.to=to; svg.appendChild(path); edgeEls.push(path); });
const nodeEls=[], planetEls=[], planetEdgeEls=[];
nodes.forEach(node=>{ const position=positions.get(node.name), group=document.createElementNS(ns,'g'); group.setAttribute('class','node'); group.dataset.name=node.name; group.dataset.tier=node.tier; group.setAttribute('transform',`translate(${position.x},${position.y})`); const rect=document.createElementNS(ns,'rect'); rect.setAttribute('width',nodeW); rect.setAttribute('height',nodeH); rect.setAttribute('rx','3'); const tier=document.createElementNS(ns,'text'); tier.setAttribute('x','10'); tier.setAttribute('y','14'); tier.setAttribute('class','tier'); tier.textContent=node.tier; const text=document.createElementNS(ns,'text'); text.setAttribute('x','10'); text.setAttribute('y','29'); text.textContent=node.name.length>25?node.name.slice(0,24)+'…':node.name; group.append(rect,tier,text); svg.appendChild(group); nodeEls.push(group); group.addEventListener('click',()=>select(node.name)); group.addEventListener('contextmenu',event=>{ event.preventDefault(); select(node.name); showContextMenu(node,event.clientX,event.clientY); }); });
p0ToP1.forEach(([name,,planets])=>{ const position=positions.get(name), planetNames=planets.split(', '); planetNames.forEach((planetName,index)=>{ const y=position.y+index*30-((planetNames.length-1)*30)/2, edge=document.createElementNS(ns,'path'); edge.setAttribute('d',`M 176 ${y+14} C 192 ${y+14}, 198 ${position.y+nodeH/2}, ${position.x} ${position.y+nodeH/2}`); edge.setAttribute('class','planet-edge'); edge.dataset.source=name; edge.dataset.index=index; svg.appendChild(edge); planetEdgeEls.push(edge); const group=document.createElementNS(ns,'g'); group.setAttribute('class','planet-node'); group.dataset.source=name; group.dataset.index=index; group.setAttribute('transform',`translate(8,${y})`); const rect=document.createElementNS(ns,'rect'); rect.setAttribute('width','168'); rect.setAttribute('height','28'); rect.setAttribute('rx','3'); const text=document.createElementNS(ns,'text'); text.setAttribute('x','10'); text.setAttribute('y','18'); text.textContent=planetName; group.append(rect,text); svg.appendChild(group); planetEls.push(group); }); });
function layoutP0(activeP0) { let nextY=78; nodes.filter(node=>node.tier==='P0').forEach(node=>{ const position=positions.get(node.name); position.y=nextY; nextY+=activeP0.has(node.name)?190:nodeH+gap; const element=nodeEls.find(item=>item.dataset.name===node.name); if (element) element.setAttribute('transform',`translate(${position.x},${position.y})`); }); edgeEls.forEach(element=>{ const start=positions.get(element.dataset.from), end=positions.get(element.dataset.to); element.setAttribute('d',`M ${start.x+nodeW} ${start.y+nodeH/2} C ${start.x+nodeW+35} ${start.y+nodeH/2}, ${end.x-35} ${end.y+nodeH/2}, ${end.x} ${end.y+nodeH/2}`); }); planetEls.forEach(element=>{ const position=positions.get(element.dataset.source), count=p0ToP1.find(([name])=>name===element.dataset.source)[2].split(', ').length, y=position.y+Number(element.dataset.index)*30-((count-1)*30)/2; element.setAttribute('transform',`translate(8,${y})`); }); planetEdgeEls.forEach(element=>{ const position=positions.get(element.dataset.source), count=p0ToP1.find(([name])=>name===element.dataset.source)[2].split(', ').length, y=position.y+Number(element.dataset.index)*30-((count-1)*30)/2; element.setAttribute('d',`M 176 ${y+14} C 192 ${y+14}, 198 ${position.y+nodeH/2}, ${position.x} ${position.y+nodeH/2}`); }); const graphHeight=Math.max(...tierNames.map(tier=>nodes.filter(node=>node.tier===tier).length?Math.max(...nodes.filter(node=>node.tier===tier).map(node=>positions.get(node.name).y+nodeH)):0))+30; svg.setAttribute('viewBox',`0 0 1410 ${Math.max(1760,graphHeight)}`); }
const adjacency = new Map(); nodes.forEach(node=>adjacency.set(node.name,{in:new Set(),out:new Set()})); edges.forEach(([from,to])=>{ adjacency.get(from).out.add(to); adjacency.get(to).in.add(from); });
let selected=null, filter='ALL';
const contextMenu=document.getElementById('contextMenu'), localJson=document.getElementById('localJson'), ccuLevel=document.getElementById('ccuLevel'); let pendingCopyName='';
const themeToggle=document.getElementById('themeToggle');
themeToggle.checked=localStorage.getItem('eve-pi-theme')==='dark';
const savedCcuLevel=localStorage.getItem('eve-pi-ccu-level');
if (['1','2','3','4','5'].includes(savedCcuLevel)) ccuLevel.value=savedCcuLevel;
function configFilesFor(node) { if (node.tier==='P0') { const p1=p0ToP1.find(([p0])=>p0===node.name)[1]; return minerFiles[p1]||[]; } if (node.tier==='P1') return minerFiles[node.name]||[]; return [`Factory/${node.tier}/${node.name === 'High-Tech Transmitters' ? 'Factory - High-Tech Transmitters.json' : `Factory - ${node.name}.json`}`]; }
function showContextMenu(node,x,y) { const files=configFilesFor(node); contextMenu.innerHTML=`<div class="context-title">${node.name} · configuration</div>`; files.forEach(path=>{ const button=document.createElement('button'); button.type='button'; button.textContent=`Copy JSON · ${path}`; button.title=path; button.addEventListener('click',()=>copyJson(path)); contextMenu.appendChild(button); }); const localButton=document.createElement('button'); localButton.type='button'; localButton.className='local'; localButton.textContent='Choose local JSON and copy'; localButton.addEventListener('click',()=>{ pendingCopyName=node.name; localJson.value=''; localJson.click(); }); contextMenu.appendChild(localButton); contextMenu.classList.add('visible'); contextMenu.setAttribute('aria-hidden','false'); contextMenu.style.left=`${Math.max(12,Math.min(x,window.innerWidth-contextMenu.offsetWidth-12))}px`; contextMenu.style.top=`${Math.max(12,Math.min(y,window.innerHeight-contextMenu.offsetHeight-12))}px`; }
function setCcuLevel(text) { const configuration=JSON.parse(text); configuration.CmdCtrLv=Number(ccuLevel.value); return JSON.stringify(configuration); }
async function copyJson(path) { try { const response=await fetch(`../PlanetaryInteractionTemplates/${path}`); if (!response.ok) throw new Error('File unavailable'); await copyText(setCcuLevel(await response.text())); closeContextMenu(); } catch { pendingCopyName=path; localJson.value=''; localJson.click(); } }
async function copyText(text) { try { if (navigator.clipboard&&window.isSecureContext) { await navigator.clipboard.writeText(text); return; } } catch { } const fallback=document.createElement('textarea'); fallback.value=text; fallback.setAttribute('readonly',''); fallback.style.position='fixed'; fallback.style.opacity='0'; document.body.appendChild(fallback); fallback.select(); const copied=document.execCommand('copy'); fallback.remove(); if (!copied) throw new Error('Clipboard unavailable'); }
localJson.addEventListener('change',async()=>{ const file=localJson.files[0]; if (!file) return; try { await copyText(setCcuLevel(await file.text())); closeContextMenu(); } catch { alert(`Unable to copy JSON for ${pendingCopyName}.`); } });
function closeContextMenu() { contextMenu.classList.remove('visible'); contextMenu.setAttribute('aria-hidden','true'); }
document.addEventListener('click',event=>{ if (!contextMenu.contains(event.target)) closeContextMenu(); }); window.addEventListener('resize',closeContextMenu);
function connected(name,direction,seen=new Set()) { if (seen.has(name)) return seen; seen.add(name); adjacency.get(name)[direction].forEach(next=>connected(next,direction,seen)); return seen; }
function select(name) { selected=selected===name?null:name; const keep=selected?new Set([selected,...connected(selected,'in'),...connected(selected,'out')]):null; nodeEls.forEach(element=>{ element.classList.toggle('selected',element.dataset.name===selected); element.classList.toggle('dimmed',!!keep&&!keep.has(element.dataset.name)); }); edgeEls.forEach(element=>{ const active=selected&&keep.has(element.dataset.from)&&keep.has(element.dataset.to); element.classList.toggle('active',!!active); element.classList.toggle('dimmed',!!selected&&!active); }); if (selected) { const node=nodeByName.get(selected), planetInfo=node.tier==='P0'?` · planets: ${node.planets}`:''; document.getElementById('meta').textContent=`${selected}${planetInfo} · inputs: ${[...adjacency.get(selected).in].join(', ')||'none'} · outputs: ${[...adjacency.get(selected).out].join(', ')||'none'}`; } else document.getElementById('meta').textContent='Select a commodity to isolate its inputs and outputs.'; const visibleP0=selected?new Set(nodes.filter(node=>node.tier==='P0'&&keep.has(node.name)).map(node=>node.name)):new Set(); layoutP0(visibleP0); planetEls.forEach(element=>element.classList.toggle('visible',visibleP0.has(element.dataset.source))); planetEdgeEls.forEach(element=>element.classList.toggle('visible',visibleP0.has(element.dataset.source))); }
function render() { const query=document.getElementById('search').value.trim().toLowerCase(); nodeEls.forEach(element=>{ const visible=(filter==='ALL'||element.dataset.tier===filter)&&(!query||element.dataset.name.toLowerCase().includes(query)); element.classList.toggle('dimmed',!visible||!!selected&&!connected(selected,'in').has(element.dataset.name)&&!connected(selected,'out').has(element.dataset.name)&&element.dataset.name!==selected); element.classList.toggle('match',!!query&&element.dataset.name.toLowerCase().includes(query)); }); edgeEls.forEach(element=>{ const visible=filter==='ALL'||nodeByName.get(element.dataset.from).tier===filter||nodeByName.get(element.dataset.to).tier===filter; element.classList.toggle('dimmed',!visible); }); }
document.getElementById('search').addEventListener('input',render); document.querySelectorAll('.tier').forEach(button=>button.addEventListener('click',()=>{ document.querySelectorAll('.tier').forEach(item=>item.classList.remove('active')); button.classList.add('active'); filter=button.dataset.filter; render(); })); themeToggle.addEventListener('change',()=>localStorage.setItem('eve-pi-theme',themeToggle.checked?'dark':'light')); ccuLevel.addEventListener('change',()=>localStorage.setItem('eve-pi-ccu-level',ccuLevel.value)); layoutP0(new Set()); render();
